import { Dimensions, StyleSheet } from 'react-native'

const { height } = Dimensions.get('window')

export const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#fff',
    position: 'relative',
  },
  header: {
    paddingVertical: 20,
    paddingHorizontal: 10,
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1a3263',
    alignSelf: 'flex-start',
  },
  viewMap: {
    width: '100%',
    height,
    overflow: 'hidden',
    borderRadius: 30,
  },
  cameraContainer: {
    flex: 1,
    position: 'relative',
    justifyContent: 'center',
    alignContent: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  detail: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
    height: 160,
    backgroundColor: '#fff',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 5,
      height: 0,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,
    paddingBottom: 0,
    elevation: 10,
  },
  title: {
    color: '#1a3263',
    fontSize: 32,
    fontWeight: 'bold',
  },
  subtitle: {
    color: '#999',
    marginHorizontal: 10,
    fontSize: 20,
    marginTop: 9,
  },
  location: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkIn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  capture: {
    position: 'absolute',
    width: 80,
    bottom: 20,
    zIndex: 999,
    height: 80,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    borderColor: 'orange',
    borderWidth: 2,
    borderRadius: 40,
    backgroundColor: '#fff',
  },
  btn: {
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    shadowColor: 'rgba(0,0,0,0.5)',
    backgroundColor: '#fff',
    elevation: 3,
  },
  navigation: {
    width: 140,
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
})
